In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Codes to Know for Code Validation
Steps: 

(Understanding the data)
1. Load the data
2. Looking the first and last 5 row
3. Shape (rows, cols) 
4. Data types of the data in columns (features)
5. Unique Values

(Info of Missing Data)
1. Find the missing value
2. Counting the number of missing values
3. Percentage missing

(Handelling the Missing Data)
1. Remove rows with missing values
2. Remove columns with missing values
3. Filling with mean and median
4. Fill with most common value

(Info of Duplicates)
1. Count the number of duplicates
2. Remove duplicates

(Selecting Data)
1. Getting one or more culumn
2. Getting first n rows
3. Getting a specific row
4. GEtting a range of rows

(Filtering the data)
1. Getting the data with a spicific condition
2. See examples

(Creating New Columns)
1. Make your own coulmn using the otehrs
2. See examples

(Sorting)
1. Sorting a spicific colunm
2. Y/N ascedning

(Aggregations)
1. Average
2. Max/Min
3. Median
4. Standard deviation

(Grouping)
(Correlation)
(Visulization)
1. Histogram of a colunm
2. Boxplot of a colunm
3. Scatter Plot

## 1. Understanding the data

In [ ]:
# 1.1 Load the data
df = pd.read_csv("data/stud.csv")

In [ ]:
# 1.2 Looking the first and last 5 row
print("First 5 rows:")
print(df.head())
print()
print()
print("Last 5 rows:")
print(df.tail())

First 5 rows:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75


Last 5 rows:
     gender race/ethnicity parental level of education         lunch  \
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

In [ ]:
# 1.3 Shape of data: (rows, cols)
df.shape

(1000, 8)

In [13]:
# 1.4: Features (cols name)
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [15]:
# 1.5 Data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [ ]:
df.describe() # Statics summary of integer data types.

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [30]:
# 1.6 Unique Values: 
print("Unique values of a categorical data: ")
print(df["race/ethnicity"].unique())
print()
print("Number of unique values:")
print(df["race/ethnicity"].nunique())

Unique values of a categorical data:
<StringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str

Number of unique values:
5

In [32]:
# 1.7: Count each category
print("Number of people in different grups of ethnicity:")
print(df["race/ethnicity"].value_counts())

Number of people in different grups of ethnicity:
race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

## 2. Info of Missing data:

In [ ]:
# 2.1 Find the missing values:
df.isna()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [43]:
# 2.2: Count the missing values in each colunm:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [44]:
# 2.3 percenatage missing in each colunm:
((df.isna().sum()) / len(df)) * 100

gender                         0.0
race/ethnicity                 0.0
parental level of education    0.0
lunch                          0.0
test preparation course        0.0
math score                     0.0
reading score                  0.0
writing score                  0.0
dtype: float64

In [45]:
# 2.4 Handeling the missing data:
# Remove rows with missing values:
df.dropna()
# Remove columns with missing values
df.dropna(axis=1)
# Fill with the mean/median in a column:
df["math score"] = df["math score"].fillna(
    df["math score"].mean() # .median()
)
# Fill with most common value
df["gender"] = df["gender"].fillna(
    df["gender"].mode()[0]
)