In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Codes to Know for Data Exploring
Steps: 

🔵 (Understanding the data)
1. Load the data
2. Looking the first and last 5 row
3. Shape (rows, cols) 
4. Data types of the data in columns (features)
5. Unique Values

🔵 (Info of Missing Data)
1. Find the missing value
2. Counting the number of missing values
3. Percentage missing

🔵 (Handelling the Missing Data)
1. Remove rows with missing values
2. Remove columns with missing values
3. Filling with mean and median
4. Fill with most common value

🔵 (Info of Duplicates)
1. Count the number of duplicates
2. Remove duplicates

🔵 (Selecting Data)
1. Getting one or more culumn
2. Getting first n rows
3. Getting a specific row
4. GEtting a range of rows

🔵 (Filtering the data)
1. Getting the data with a spicific condition
2. See examples

🔵 (Creating New Columns)
1. Make your own coulmn using the otehrs
2. See examples

🔵 (Sorting)
1. Sorting a spicific colunm
2. Y/N ascedning

🔵 (Aggregations)
1. Average
2. Max/Min
3. Median
4. Standard deviation

🔵 <span style="color:red"> (Grouping) </span> **VERY IMPORTANT**
(Correlation)

## 1. Understanding the data
1. Load the data
2. Looking the first and last 5 row
3. Shape (rows, cols) 
4. Data types of the data in columns (features)
5. Unique Values

In [35]:
# 1.1 Load the data
df = pd.read_csv("data/stud.csv")

In [36]:
# 1.2 Looking the first and last 5 row
print("First 5 rows:")
print(df.head())
print()
print()
print("Last 5 rows:")
print(df.tail())

First 5 rows:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75


Last 5 rows:
     gender race/ethnicity parental level of education         lunch  \
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

In [37]:
# 1.3 Shape of data: (rows, cols)
df.shape # output: (1000, 8)

(1000, 8)

In [38]:
# 1.4: Features (cols name)
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [39]:
# 1.5 Data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [40]:
df.describe() # Statics summary of integer data types.

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [41]:
# 1.6 Unique Values: 
print("Unique values of a categorical data: ")
print(df["race/ethnicity"].unique())
print()
print("Number of unique values:")
print(df["race/ethnicity"].nunique())

Unique values of a categorical data:
<StringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str

Number of unique values:
5

In [42]:
# 1.7: Count each category
print("Number of people in different grups of ethnicity:")
print(df["race/ethnicity"].value_counts())

Number of people in different grups of ethnicity:
race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

## 2. Info of Missing data:
1. Find the missing value
2. Counting the number of missing values
3. Percentage missing

In [43]:
# 2.1 Find the missing values:
df.isna()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [44]:
# 2.2: Count the missing values in each colunm:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [45]:
# 2.3 percenatage missing in each colunm:
((df.isna().sum()) / len(df)) * 100

gender                         0.0
race/ethnicity                 0.0
parental level of education    0.0
lunch                          0.0
test preparation course        0.0
math score                     0.0
reading score                  0.0
writing score                  0.0
dtype: float64

## 3. Handelling the Missing Data
1. Remove rows with missing values
2. Remove columns with missing values
3. Filling with mean and median
4. Fill with most common value

In [46]:
# 3.1 Remove rows with missing values:
df.dropna()

# 3.2 Remove columns with missing values
df.dropna(axis=1)

# 3.3 Fill with the mean/median in a column:
df["math score"] = df["math score"].fillna(
    df["math score"].mean() # .median()
)

# 3.4 Fill with most common value
df["gender"] = df["gender"].fillna(
    df["gender"].mode()[0]
)

## 4. Info of Duplicates
1. Count the number of duplicates
2. Remove duplicates

In [47]:
# 4.1 Count the duplicates
print(df.duplicated().sum())

# 4.2 Remove the duplicate
df.drop_duplicates()

0

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

## 5. Selecting Data
1. Getting one or more culumn
2. Getting first n rows
3. Getting a specific row
4. GEtting a range of rows

In [48]:
# 5.1 Getting one or more column:
df["math score"] # one column
df[["math score", "reading score"]] # mult column

# 5.2 Getting the first n rows: (n = 3)
df.head(3)

# 5.3 Getting a specific row:
df.iloc[167] # getting row 167th

# 5.4 Getting a range of rows: 
df.iloc[160:168] # row 160-168

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78

## 6. Filtering the data
1. Getting the data with a spicific condition
2. See examples

In [49]:
# 6.1 students with math score > 80:
df[df["math score"] > 80]

# 6.2 Female students:
df[df["gender"] == "female"]

# 6.3 students with math AND reading > 80:
df[
    (df["math score"] > 80)
    & 
    (df["reading score"] > 80)
]
# Note: either condition would be: | (means or)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
6,female,group B,some college,standard,completed,88,95,92
16,male,group C,high school,standard,none,88,89,86
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
...,...,...,...,...,...,...,...,...
962,female,group E,associate's degree,standard,none,100,100,100
970,female,group D,bachelor's degree,standard,none,89,100,100
979,female,group C,associate's degree,standard,none,91,95,94
990,male,group E,high school,free/reduced,completed,86,81,75
995,female,group E,master's degree,standard,completed,88,99,95

## 7. Creating New Columns
1. Make your own coulmn using the otehrs
2. See examples

In [50]:
# 7.1 Make your own column:
df["average"] = (df["math score"] + df["reading score"] + df["writing score"]) / 3

# 7.2 pass or fail:
df["passed"] = df["average"] >= 50

## 8. Sorting
1. Sorting a spicific colunm
    * `sort_values(factor, ascending=T/F)` will return a new DataFrame and it won't modify the previous one, so to see the result we have to create a new DF and assign its values to that. 
2. Y/N ascedning

In [51]:
# 8.1 Sorting a specific column:
first_11_df = df.iloc[0:11].copy() # making the data smaller for faster computation
sorted_df_asc = first_11_df.sort_values("math score") 
sorted_df_desc = first_11_df.sort_values("math score", ascending=False) 

# print("Low to High")
# print(sorted_df["math score"])
# print()
# print("High to Low")
print(sorted_df_desc["math score"])

2     90
6     88
4     76
0     72
5     71
1     69
8     64
10    58
3     47
7     40
9     38
Name: math score, dtype: int64

## 9. Aggregations
1. Average/mean
2. Max/Min
3. Median
4. Standard deviation

In [52]:
# 9.1: Average:
print("Information of math grades:")
print("Average: {} \nMax: {} \nMin: {} \nMedian: {} \nSTD: {}".format(
    df["math score"].mean(), 
    df["math score"].max(), 
    df["math score"].min(), 
    df["math score"].median(), 
    df["math score"].std(), 
    ))

Information of math grades:
Average: 66.089
Max: 100
Min: 0
Median: 66.0
STD: 15.16308009600945

## 10. Grouping + Correlation

In [53]:
# VERY IMPORTANT:
# 10.1 Average math score by gender
print(df.groupby("gender")["math score"].mean())

print()
# 10.2 grouping the min reading score by race
print(df.groupby("race/ethnicity")["reading score"].min())

print()
# Correlation: Useful for seeing how strongly numerical variables are related.
print(df.corr(numeric_only=True))

gender
female    63.633205
male      68.728216
Name: math score, dtype: float64

race/ethnicity
group A    23
group B    24
group C    17
group D    31
group E    26
Name: reading score, dtype: int64

               math score  reading score  writing score   average    passed
math score       1.000000       0.817580       0.802642  0.918746  0.549460
reading score    0.817580       1.000000       0.954598  0.970331  0.594595
writing score    0.802642       0.954598       1.000000  0.965667  0.600787
average          0.918746       0.970331       0.965667  1.000000  0.611196
passed           0.549460       0.594595       0.600787  0.611196  1.000000